---
- include: requirements.yml

- name: Create user
  user: name="{{ moodle_user }}"

- name: Create moodle directry
  file: dest="{{ moodle_path }}" state=directory owner="{{ moodle_user }}"


- name: Getting Moodle
  git: repo=https://github.com/moodle/moodle.git version="{{ moodle_version }}" dest="{{ moodle_src }}" accept_hostkey=yes

- name: Configure Moodle
  template: src=config.php.j2 dest="{{ moodle_src }}/config.php"

- name: Create moodle docs directry
  file: dest="{{ moodle_docs }}" state=directory owner="{{ moodle_user }}"

- name: Set up cron
  cron: name="Moodle" job="/usr/bin/php {{ moodle_path }}/admin/cli/cron.php >/dev/null" 


  
